// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRY4EBZkroApJtsZ1qRMzUpfAmDNben78',
    appId: '1:87313991339:web:3de1cd6c749bbb1a50d9ee',
    messagingSenderId: '87313991339',
    projectId: 'flutter-contact-853e3',
    authDomain: 'flutter-contact-853e3.firebaseapp.com',
    storageBucket: 'flutter-contact-853e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-f_cQ7BeopqEdUyuRLl2-sRPU7UUpVI',
    appId: '1:87313991339:android:7f27a18fbfc957f950d9ee',
    messagingSenderId: '87313991339',
    projectId: 'flutter-contact-853e3',
    storageBucket: 'flutter-contact-853e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UEAtHu7DYjtswwl5qBXHIHgIEonoQ7g',
    appId: '1:87313991339:ios:2f14a71fd0d0b39050d9ee',
    messagingSenderId: '87313991339',
    projectId: 'flutter-contact-853e3',
    storageBucket: 'flutter-contact-853e3.appspot.com',
    iosBundleId: 'com.example.contactlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UEAtHu7DYjtswwl5qBXHIHgIEonoQ7g',
    appId: '1:87313991339:ios:999d312e1a40538d50d9ee',
    messagingSenderId: '87313991339',
    projectId: 'flutter-contact-853e3',
    storageBucket: 'flutter-contact-853e3.appspot.com',
    iosBundleId: 'com.example.contactlist.RunnerTests',
  );
}
